name: Auto Apply Jobs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"  # runs daily at 8:30 AM IST

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Auto Applier
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python main.py

      - name: Upload log file
        uses: actions/upload-artifact@v4
        with:
          name: application-log
          path: applied_*.txt
          
      - name: Commit applied_jobs.json and skipped logs if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git pull

          mkdir -p logs/skipped
          mv skipped_manual_*.txt logs/skipped/ 2>/dev/null || true
          git add applied_jobs.json logs/skipped/*.txt

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m 'Update applied_jobs.json and skipped logs after applying jobs'
            git push origin HEAD:${{ github.ref }}
